---
title: "DataForDash-1\3"
author: "Qianqi Wei"
date: '2023-03-03'
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
setwd("C:/Users/67351/OneDrive/文档/UW/2022-9/winter/543/Final Report/Dashboard")
```


When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r Deliverable 1}
library(rio)
library(DescTools)
Link = "https://github.com/Highhighhand/Deliverable-1/raw/main/LifeExpect_birth.xlsx"
cia = import(Link)
cia
write.csv(cia,"cia.csv")
```



```{r Deliverable 3}
link="https://github.com/Highhighhand/Deliverable-3/raw/main/LifeExpect_birth.xlsx"
library(rio)

cia3=import(link)
segmented_data = data.frame(cia3$name,
                 cut(cia3$value, c(0,60,70,80,90), labels=c("<60","60~70","70~80",">80"),
                     include.lowest = TRUE, right = FALSE))
names(segmented_data) = c('NAME', 'value')
segmented_data

linkMap="https://github.com/Highhighhand/Deliverable-3/raw/main/worldMap.geojson" 
library(sf)
mapWorld=read_sf(linkMap)
str(mapWorld)
map_values=merge(mapWorld,
                   segmented_data, 
                   by='NAME')
write.csv(mapWorld,"mapWorld.csv")
write.csv(map_values,"map_values.csv")
```

