---
title: "PlotForDash-13"
author: "Qianqi Wei"
date: '2023-03-03'
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
```


```{r Deliverable 1}
library(rio)
library(ggplot2)
library(DescTools)

cia=read.csv("cia.csv")
WIDTH=1

base= ggplot(cia)  
h1= base + geom_histogram(aes(x = value),
                          binwidth = WIDTH,
                          fill='grey') 
h1=h1 + labs(y="Count") + labs(x="Life Expectancy")
mn=Mean(cia$value,na.rm = T)
sk=Skew(cia$value,
     na.rm = T)

annMean=paste0('Mean:',round(mn))
annSk=paste0('Skewness:',round(sk,2))

h2 = h1+ geom_vline(xintercept = mn,color='red') + 
    annotate(geom = 'text',color='red',
             label=annMean,
              y = 15,
              x=mn-3,
              angle=90) + 
    annotate(geom = 'text', color='blue',
             label=annSk,
              y = 5,
              x= 88,
              angle=0) +
    labs(title="What is the life expectancy in the world",
          caption = "Resource: Worldometer data")
h2
saveRDS(h2, file = "h2.rds")
```

## Including Plots


```{r Deliverable 3}
link="https://github.com/Highhighhand/Deliverable-3/raw/main/LifeExpect_birth.xlsx"
library(rio)

cia=import(link)

segmented_data = data.frame(cia$name,
                            cut(cia$value, c(0,60,70,80,90), labels=c("<60","60~70","70~80",">80"),
                                include.lowest = TRUE, right = FALSE))
names(segmented_data) = c('NAME', 'value')
segmented_data

linkMap="https://github.com/Highhighhand/Deliverable-3/raw/main/worldMap.geojson" 

library(sf)
mapWorld=read_sf(linkMap)
str(mapWorld)
map_values=merge(mapWorld,
                 segmented_data, 
                 by='NAME')
library(ggplot2)
baseMap= ggplot(data=mapWorld) + theme_classic() + 
  geom_sf(fill='grey', 
          color=NA) 
baseMap 
numericMap= baseMap + geom_sf(data=map_values,
                              aes(fill=value),
                              color=NA)
numericMap
Legend_title="Life Expectancy\n(grey is missing)"
titleText='What is the life expectancy in different countries around the world?'
sourceText='Source: Canvas data Life expectancy at birth'
numericmap1=numericMap + scale_fill_brewer(palette ='YlOrBr', name=Legend_title)+labs(title=titleText,caption=sourceText)
numericmap1
saveRDS(numericmap1,"numericmap1.rds")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
